### PR TITLE
Add Portuguese list of words.

### PR DESCRIPTION
**Pull request by ajdavidl**
I made 3 changes:

1. Added a list of Portuguese words.
  - The list was made by São Paulo University.
  - This is the [link](https://www.ime.usp.br/~pf/dicios/br-utf8.txt) of the original list.
  - This is the [link](https://www.ime.usp.br/~pf/dicios/index.html) of main page. (It's in Portuguese. I couldn't find the English version, sorry.)

2. Changed the WordLists.jl file to support Portuguese.

3. Update the test file.

### CODE REVIEW

**Comment by LilithHafner** [comment]
Thank you!

Please also change the list of currently supported languages in the README, we want folks to know that Portuguese is now an option!

The word lists should be sorted and this one is not quite sorted. For example "adequáveis" comes before "adequei" despite "ebulição" coming before "ábaco". Ideally, we would use Julia's `<` operator to determine ordering, though if there is a compelling linguistic reason to use a different order that would complicate things. If you think that the ordering discrepancies are an oversight rather than a linguistically justified decision, you can fix them with

```julia
open("sorted_words.txt", "w") do io
    println.(io, sort!(readlines("words.txt")))
end;
```

We should also test that the word lists are sorted. It was an oversight to not test that the Spanish list is sorted.

**Comment by LilithHafner** [comment]
I added better sorting tests to catch this kind of mistake more reliably in the future. Now all that is needed to add sorting tests for a new language is to add to the list of languages in the sorting & whitespace testset.

I also noticed that at least a few words are missing. I do not have knowledge of Portuguese, so perhaps these aren't words at all, but "cafuné", "contêm", "desbundar", "lavagem", and "xodó" are not in this list. It's tricky to come up with a list that has all the words, though, and I would be happy to merge this with an acknowledgement that the word list is incomplete. For example, changing "the list of Spanish words is incomplete" to "the lists of Spanish and Portuguese words are incomplete" in the readme.

**Comment by ajdavidl** [comment]
I made 3 updates:

1. I added Portuguese to "issorted & !isspace" test;
2. I updated the README file;
3. I sorted the list as you said.

**Comment by LilithHafner** [comment]
Thank you for your contribution! It's great to have another language supported :)

**Pull request merged**
